// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBg9cAxpnuyzD-e9_3DUGdof_JyiqeUFCw',
    appId: '1:943867506990:web:4a3114be8d6405ffb68abf',
    messagingSenderId: '943867506990',
    projectId: 'coding-application-8cfdf',
    authDomain: 'coding-application-8cfdf.firebaseapp.com',
    storageBucket: 'coding-application-8cfdf.appspot.com',
    measurementId: 'G-KQD6DSTWNK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBTpiClwj0ZxQ3VQqhEvz6S8KdMhcW1qsY',
    appId: '1:943867506990:android:f330bd4c2f3bb753b68abf',
    messagingSenderId: '943867506990',
    projectId: 'coding-application-8cfdf',
    storageBucket: 'coding-application-8cfdf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDXSwknyTThG0eqOruiUOlpaTKImMiZos',
    appId: '1:943867506990:ios:a1134b05d7486193b68abf',
    messagingSenderId: '943867506990',
    projectId: 'coding-application-8cfdf',
    storageBucket: 'coding-application-8cfdf.appspot.com',
    iosBundleId: 'bcastudy.example.bcastudy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDXSwknyTThG0eqOruiUOlpaTKImMiZos',
    appId: '1:943867506990:ios:a1134b05d7486193b68abf',
    messagingSenderId: '943867506990',
    projectId: 'coding-application-8cfdf',
    storageBucket: 'coding-application-8cfdf.appspot.com',
    iosBundleId: 'bcastudy.example.bcastudy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBg9cAxpnuyzD-e9_3DUGdof_JyiqeUFCw',
    appId: '1:943867506990:web:570657430cf9090cb68abf',
    messagingSenderId: '943867506990',
    projectId: 'coding-application-8cfdf',
    authDomain: 'coding-application-8cfdf.firebaseapp.com',
    storageBucket: 'coding-application-8cfdf.appspot.com',
    measurementId: 'G-MMYJYJKF5Y',
  );
}
